### ISSUE TITLE
Cannot write to Google sheets

### ISSUE THREAD

**Issue by BarishNamazov** [madatajs/madata#32]
It looks like when connecting to Google sheets, the writes are being blocked. Try to click on save in this pen: https://codepen.io/toonewbie/pen/xxaweBd

**Comment by BarishNamazov** [comment]
@DmitrySharabin we are using this for assignment in DesignFTW, would you be able to prioritize this issue? Happy to help!

**Comment by DmitrySharabin** [comment]
Hey @BarishNamazov,

Unfortunately, writing back to a spreadsheet (as well as reading/writing to a private spreadsheet) demands the user be authenticated. That's why it fails. Even though a spreadsheet is public and everybody can write to it, this is possible only via the Google Sheets UI, not via the API we use with MaData under the hood. I’m sorry. 😔

**Comment by BarishNamazov** [comment]
I see, interesting design choice by Google APIs. I'll note it, thanks!
